// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BddE2eTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Restart Scenarios")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class RestartScenariosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Restart Scenarios", "As a system integrator\r\nI want to verify that the system handles restarts correct" +
                "ly\r\nSo that messages are not lost or duplicated when components restart", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ComponentsRestart.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ComponentsRestart.feature.ndjson", 6);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Delivery after subscriber restart using committed offset")]
        public async global::System.Threading.Tasks.Task DeliveryAfterSubscriberRestartUsingCommittedOffset()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delivery after subscriber restart using committed offset", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table1.AddRow(new string[] {
                            "Topic",
                            "default"});
                table1.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table1.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table1.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table1.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("a publisher is configured with the following options:", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table2.AddRow(new string[] {
                            "Topic",
                            "default"});
                table2.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table2.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table2.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 14
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table2, "And ");
#line hidden
#line 20
        await testRunner.WhenAsync("the publisher sends 6 messages to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
        await testRunner.ThenAsync("subscriber C consumed messages up to offset 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
        await testRunner.WhenAsync("subscriber C restarts at offset 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
        await testRunner.ThenAsync("a subscriber receives message \"msg5\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
        await testRunner.WhenAsync("the publisher sends message \"resume-test\" to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
        await testRunner.ThenAsync("a subscriber receives message \"resume-test\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Delivery after broker restart")]
        public async global::System.Threading.Tasks.Task DeliveryAfterBrokerRestart()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delivery after broker restart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table3.AddRow(new string[] {
                            "Topic",
                            "default"});
                table3.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table3.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table3.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table3.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 28
        await testRunner.GivenAsync("a publisher is configured with the following options:", ((string)(null)), table3, "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table4.AddRow(new string[] {
                            "Topic",
                            "default"});
                table4.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table4.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table4.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 35
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table4, "And ");
#line hidden
#line 41
        await testRunner.WhenAsync("the publisher sends 6 messages to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
        await testRunner.ThenAsync("subscriber C consumed messages up to offset 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
        await testRunner.WhenAsync("the broker restarts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
        await testRunner.ThenAsync("a subscriber receives message \"msg5\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
        await testRunner.WhenAsync("the publisher sends message \"resume-test\" to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
        await testRunner.ThenAsync("a subscriber receives message \"resume-test\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Delivery after publisher restart")]
        public async global::System.Threading.Tasks.Task DeliveryAfterPublisherRestart()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delivery after publisher restart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table5.AddRow(new string[] {
                            "Topic",
                            "default"});
                table5.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table5.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table5.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table5.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 49
        await testRunner.GivenAsync("a publisher is configured with the following options:", ((string)(null)), table5, "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table6.AddRow(new string[] {
                            "Topic",
                            "default"});
                table6.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table6.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table6.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 56
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table6, "And ");
#line hidden
#line 62
        await testRunner.WhenAsync("the publisher sends 6 messages to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
        await testRunner.ThenAsync("subscriber C consumed messages up to offset 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
        await testRunner.WhenAsync("the publisher restarts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
        await testRunner.ThenAsync("a subscriber receives message \"msg5\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
        await testRunner.WhenAsync("the publisher sends message \"resume-test\" to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
        await testRunner.ThenAsync("a subscriber receives message \"resume-test\" from topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Publisher continues sending messages during broker restart")]
        public async global::System.Threading.Tasks.Task PublisherContinuesSendingMessagesDuringBrokerRestart()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Publisher continues sending messages during broker restart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table7.AddRow(new string[] {
                            "Topic",
                            "default"});
                table7.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table7.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table7.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table7.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 70
        await testRunner.GivenAsync("a publisher is configured with the following options:", ((string)(null)), table7, "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table8.AddRow(new string[] {
                            "Topic",
                            "default"});
                table8.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table8.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table8.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 77
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table8, "And ");
#line hidden
#line 83
        await testRunner.WhenAsync("the publisher sends 10 messages to topic \"default\" and the broker restarts after " +
                        "3 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
        await testRunner.ThenAsync("subscriber C consumed messages up to offset 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
