// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Multiple Topics Publisher and Subscriber Communication")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MultipleTopicsPublisherAndSubscriberCommunicationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Multiple Topics Publisher and Subscriber Communication", "    As a system integrator\r\n    I want to verify that multiple publishers and sub" +
                "scribers can communicate across different topics simultaneously\r\n    So that the" +
                " message broker correctly isolates and routes messages per topic without cross-c" +
                "ontamination", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "MultipleTopics.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple publishers and subscribers across multiple topics simultaneously")]
        public async System.Threading.Tasks.Task MultiplePublishersAndSubscribersAcrossMultipleTopicsSimultaneously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple publishers and subscribers across multiple topics simultaneously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table20.AddRow(new string[] {
                            "Topic",
                            "default"});
                table20.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table20.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table20.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table20.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("publishers A1, B1, C1 are configured with the following options:", ((string)(null)), table20, "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table21.AddRow(new string[] {
                            "Topic",
                            "default"});
                table21.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table21.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table21.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 14
        await testRunner.AndAsync("subscribers D1, E1, F1 are configured with the following options:", ((string)(null)), table21, "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table22.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table22.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table22.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table22.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table22.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 20
        await testRunner.AndAsync("publishers A2, B2, C2 are configured with the following options:", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table23.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table23.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table23.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table23.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 27
        await testRunner.AndAsync("subscribers D2, E2, F2 are configured with the following options:", ((string)(null)), table23, "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table24.AddRow(new string[] {
                            "Topic",
                            "custom-topic"});
                table24.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table24.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table24.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table24.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 33
        await testRunner.AndAsync("publishers A3, B3, C3 are configured with the following options:", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table25.AddRow(new string[] {
                            "Topic",
                            "custom-topic"});
                table25.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table25.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table25.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 40
        await testRunner.AndAsync("subscribers D3, E3, F3 are configured with the following options:", ((string)(null)), table25, "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table26.AddRow(new string[] {
                            "d1"});
                table26.AddRow(new string[] {
                            "d2"});
                table26.AddRow(new string[] {
                            "d3"});
#line 46
        await testRunner.WhenAsync("the publisher A1 sends messages in order:", ((string)(null)), table26, "When ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table27.AddRow(new string[] {
                            "d4"});
                table27.AddRow(new string[] {
                            "d5"});
                table27.AddRow(new string[] {
                            "d6"});
#line 51
        await testRunner.AndAsync("the publisher B1 sends messages in order:", ((string)(null)), table27, "And ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table28.AddRow(new string[] {
                            "d7"});
                table28.AddRow(new string[] {
                            "d8"});
                table28.AddRow(new string[] {
                            "d9"});
#line 56
        await testRunner.AndAsync("the publisher C1 sends messages in order:", ((string)(null)), table28, "And ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table29.AddRow(new string[] {
                            "t1"});
                table29.AddRow(new string[] {
                            "t2"});
                table29.AddRow(new string[] {
                            "t3"});
#line 61
        await testRunner.AndAsync("the publisher A2 sends messages in order:", ((string)(null)), table29, "And ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table30.AddRow(new string[] {
                            "t4"});
                table30.AddRow(new string[] {
                            "t5"});
                table30.AddRow(new string[] {
                            "t6"});
#line 66
        await testRunner.AndAsync("the publisher B2 sends messages in order:", ((string)(null)), table30, "And ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table31.AddRow(new string[] {
                            "t7"});
                table31.AddRow(new string[] {
                            "t8"});
                table31.AddRow(new string[] {
                            "t9"});
#line 71
        await testRunner.AndAsync("the publisher C2 sends messages in order:", ((string)(null)), table31, "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table32.AddRow(new string[] {
                            "c1"});
                table32.AddRow(new string[] {
                            "c2"});
                table32.AddRow(new string[] {
                            "c3"});
#line 76
        await testRunner.AndAsync("the publisher A3 sends messages in order:", ((string)(null)), table32, "And ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table33.AddRow(new string[] {
                            "c4"});
                table33.AddRow(new string[] {
                            "c5"});
                table33.AddRow(new string[] {
                            "c6"});
#line 81
        await testRunner.AndAsync("the publisher B3 sends messages in order:", ((string)(null)), table33, "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table34.AddRow(new string[] {
                            "c7"});
                table34.AddRow(new string[] {
                            "c8"});
                table34.AddRow(new string[] {
                            "c9"});
#line 86
        await testRunner.AndAsync("the publisher C3 sends messages in order:", ((string)(null)), table34, "And ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table35.AddRow(new string[] {
                            "d1"});
                table35.AddRow(new string[] {
                            "d2"});
                table35.AddRow(new string[] {
                            "d3"});
                table35.AddRow(new string[] {
                            "d4"});
                table35.AddRow(new string[] {
                            "d5"});
                table35.AddRow(new string[] {
                            "d6"});
                table35.AddRow(new string[] {
                            "d7"});
                table35.AddRow(new string[] {
                            "d8"});
                table35.AddRow(new string[] {
                            "d9"});
#line 91
        await testRunner.ThenAsync("the subscriber D1 receives messages:", ((string)(null)), table35, "Then ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table36.AddRow(new string[] {
                            "d1"});
                table36.AddRow(new string[] {
                            "d2"});
                table36.AddRow(new string[] {
                            "d3"});
                table36.AddRow(new string[] {
                            "d4"});
                table36.AddRow(new string[] {
                            "d5"});
                table36.AddRow(new string[] {
                            "d6"});
                table36.AddRow(new string[] {
                            "d7"});
                table36.AddRow(new string[] {
                            "d8"});
                table36.AddRow(new string[] {
                            "d9"});
#line 102
        await testRunner.AndAsync("the subscriber E1 receives messages:", ((string)(null)), table36, "And ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table37.AddRow(new string[] {
                            "d1"});
                table37.AddRow(new string[] {
                            "d2"});
                table37.AddRow(new string[] {
                            "d3"});
                table37.AddRow(new string[] {
                            "d4"});
                table37.AddRow(new string[] {
                            "d5"});
                table37.AddRow(new string[] {
                            "d6"});
                table37.AddRow(new string[] {
                            "d7"});
                table37.AddRow(new string[] {
                            "d8"});
                table37.AddRow(new string[] {
                            "d9"});
#line 113
        await testRunner.AndAsync("the subscriber F1 receives messages:", ((string)(null)), table37, "And ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table38.AddRow(new string[] {
                            "t1"});
                table38.AddRow(new string[] {
                            "t2"});
                table38.AddRow(new string[] {
                            "t3"});
                table38.AddRow(new string[] {
                            "t4"});
                table38.AddRow(new string[] {
                            "t5"});
                table38.AddRow(new string[] {
                            "t6"});
                table38.AddRow(new string[] {
                            "t7"});
                table38.AddRow(new string[] {
                            "t8"});
                table38.AddRow(new string[] {
                            "t9"});
#line 124
        await testRunner.AndAsync("the subscriber D2 receives messages:", ((string)(null)), table38, "And ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table39.AddRow(new string[] {
                            "t1"});
                table39.AddRow(new string[] {
                            "t2"});
                table39.AddRow(new string[] {
                            "t3"});
                table39.AddRow(new string[] {
                            "t4"});
                table39.AddRow(new string[] {
                            "t5"});
                table39.AddRow(new string[] {
                            "t6"});
                table39.AddRow(new string[] {
                            "t7"});
                table39.AddRow(new string[] {
                            "t8"});
                table39.AddRow(new string[] {
                            "t9"});
#line 135
        await testRunner.AndAsync("the subscriber E2 receives messages:", ((string)(null)), table39, "And ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table40.AddRow(new string[] {
                            "t1"});
                table40.AddRow(new string[] {
                            "t2"});
                table40.AddRow(new string[] {
                            "t3"});
                table40.AddRow(new string[] {
                            "t4"});
                table40.AddRow(new string[] {
                            "t5"});
                table40.AddRow(new string[] {
                            "t6"});
                table40.AddRow(new string[] {
                            "t7"});
                table40.AddRow(new string[] {
                            "t8"});
                table40.AddRow(new string[] {
                            "t9"});
#line 146
        await testRunner.AndAsync("the subscriber F2 receives messages:", ((string)(null)), table40, "And ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table41.AddRow(new string[] {
                            "c1"});
                table41.AddRow(new string[] {
                            "c2"});
                table41.AddRow(new string[] {
                            "c3"});
                table41.AddRow(new string[] {
                            "c4"});
                table41.AddRow(new string[] {
                            "c5"});
                table41.AddRow(new string[] {
                            "c6"});
                table41.AddRow(new string[] {
                            "c7"});
                table41.AddRow(new string[] {
                            "c8"});
                table41.AddRow(new string[] {
                            "c9"});
#line 157
        await testRunner.AndAsync("the subscriber D3 receives messages:", ((string)(null)), table41, "And ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table42.AddRow(new string[] {
                            "c1"});
                table42.AddRow(new string[] {
                            "c2"});
                table42.AddRow(new string[] {
                            "c3"});
                table42.AddRow(new string[] {
                            "c4"});
                table42.AddRow(new string[] {
                            "c5"});
                table42.AddRow(new string[] {
                            "c6"});
                table42.AddRow(new string[] {
                            "c7"});
                table42.AddRow(new string[] {
                            "c8"});
                table42.AddRow(new string[] {
                            "c9"});
#line 168
        await testRunner.AndAsync("the subscriber E3 receives messages:", ((string)(null)), table42, "And ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table43.AddRow(new string[] {
                            "c1"});
                table43.AddRow(new string[] {
                            "c2"});
                table43.AddRow(new string[] {
                            "c3"});
                table43.AddRow(new string[] {
                            "c4"});
                table43.AddRow(new string[] {
                            "c5"});
                table43.AddRow(new string[] {
                            "c6"});
                table43.AddRow(new string[] {
                            "c7"});
                table43.AddRow(new string[] {
                            "c8"});
                table43.AddRow(new string[] {
                            "c9"});
#line 179
        await testRunner.AndAsync("the subscriber F3 receives messages:", ((string)(null)), table43, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
