// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Multiple Publisher and Subscriber Communication")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MultiplePublisherAndSubscriberCommunicationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Multiple Publisher and Subscriber Communication", "    As a system integrator\r\n    I want to verify that multiple publishers can sen" +
                "d messages and multiple subscribers can receive them\r\n    So that the message br" +
                "oker correctly routes messages between multiple components", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "MultiplePublisherSubscriber.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple Publisher Subscriber")]
        public async System.Threading.Tasks.Task MultiplePublisherSubscriber()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple Publisher Subscriber", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table11.AddRow(new string[] {
                            "Topic",
                            "default"});
                table11.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table11.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table11.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table11.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("publishers A, B, C are configured with the following options:", ((string)(null)), table11, "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table12.AddRow(new string[] {
                            "Topic",
                            "default"});
                table12.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table12.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table12.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 14
        await testRunner.AndAsync("subscribers D, E, F are configured with the following options:", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table13.AddRow(new string[] {
                            "p1"});
                table13.AddRow(new string[] {
                            "p2"});
                table13.AddRow(new string[] {
                            "p3"});
#line 20
        await testRunner.WhenAsync("the publisher A sends messages in order:", ((string)(null)), table13, "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table14.AddRow(new string[] {
                            "p4"});
                table14.AddRow(new string[] {
                            "p5"});
                table14.AddRow(new string[] {
                            "p6"});
#line 25
        await testRunner.WhenAsync("the publisher B sends messages in order:", ((string)(null)), table14, "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table15.AddRow(new string[] {
                            "p7"});
                table15.AddRow(new string[] {
                            "p8"});
                table15.AddRow(new string[] {
                            "p9"});
#line 30
        await testRunner.WhenAsync("the publisher C sends messages in order:", ((string)(null)), table15, "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table16.AddRow(new string[] {
                            "p1"});
                table16.AddRow(new string[] {
                            "p2"});
                table16.AddRow(new string[] {
                            "p3"});
                table16.AddRow(new string[] {
                            "p4"});
                table16.AddRow(new string[] {
                            "p5"});
                table16.AddRow(new string[] {
                            "p6"});
                table16.AddRow(new string[] {
                            "p7"});
                table16.AddRow(new string[] {
                            "p8"});
                table16.AddRow(new string[] {
                            "p9"});
#line 35
        await testRunner.ThenAsync("the subscriber D receives messages:", ((string)(null)), table16, "Then ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table17.AddRow(new string[] {
                            "p1"});
                table17.AddRow(new string[] {
                            "p2"});
                table17.AddRow(new string[] {
                            "p3"});
                table17.AddRow(new string[] {
                            "p4"});
                table17.AddRow(new string[] {
                            "p5"});
                table17.AddRow(new string[] {
                            "p6"});
                table17.AddRow(new string[] {
                            "p7"});
                table17.AddRow(new string[] {
                            "p8"});
                table17.AddRow(new string[] {
                            "p9"});
#line 46
        await testRunner.ThenAsync("the subscriber E receives messages:", ((string)(null)), table17, "Then ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table18.AddRow(new string[] {
                            "p1"});
                table18.AddRow(new string[] {
                            "p2"});
                table18.AddRow(new string[] {
                            "p3"});
                table18.AddRow(new string[] {
                            "p4"});
                table18.AddRow(new string[] {
                            "p5"});
                table18.AddRow(new string[] {
                            "p6"});
                table18.AddRow(new string[] {
                            "p7"});
                table18.AddRow(new string[] {
                            "p8"});
                table18.AddRow(new string[] {
                            "p9"});
#line 57
        await testRunner.ThenAsync("the subscriber F receives messages:", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
