// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Performance Measurement")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PerformanceMeasurementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Performance Measurement", "    As a system operator\n    I want to measure message broker performance under v" +
                "arious loads\n    So that I can analyze throughput, latency, and reliability metr" +
                "ics", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "PerformanceMeasurement.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Measure throughput at 100 msg/s for 30 seconds")]
        [NUnit.Framework.CategoryAttribute("performance")]
        public async System.Threading.Tasks.Task MeasureThroughputAt100MsgSFor30Seconds()
        {
            string[] tagsOfScenario = new string[] {
                    "performance"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Measure throughput at 100 msg/s for 30 seconds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await testRunner.GivenAsync("the scenario name is \"throughput_100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
        await testRunner.AndAsync("the report output directory is \"perf_reports\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table43.AddRow(new string[] {
                            "Topic",
                            "default"});
                table43.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table43.AddRow(new string[] {
                            "Queue Size",
                            "10000"});
#line 10
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table43, "And ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table44.AddRow(new string[] {
                            "Topic",
                            "default"});
                table44.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table44.AddRow(new string[] {
                            "Poll Interval",
                            "50"});
#line 15
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table44, "And ");
#line hidden
#line 20
        await testRunner.AndAsync("a constant load of 100 messages per second for 30 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.WhenAsync("the performance measurement is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Measure throughput at 500 msg/s for 60 seconds")]
        [NUnit.Framework.CategoryAttribute("performance")]
        public async System.Threading.Tasks.Task MeasureThroughputAt500MsgSFor60Seconds()
        {
            string[] tagsOfScenario = new string[] {
                    "performance"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Measure throughput at 500 msg/s for 60 seconds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
        await testRunner.GivenAsync("the scenario name is \"throughput_500\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
        await testRunner.AndAsync("the report output directory is \"perf_reports\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table45.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table45.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table45.AddRow(new string[] {
                            "Queue Size",
                            "50000"});
#line 27
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table45, "And ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table46.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table46.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table46.AddRow(new string[] {
                            "Poll Interval",
                            "25"});
#line 32
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table46, "And ");
#line hidden
#line 37
        await testRunner.AndAsync("a constant load of 500 messages per second for 60 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.WhenAsync("the performance measurement is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Long-running stability test at 200 msg/s for 2 minutes")]
        [NUnit.Framework.CategoryAttribute("performance")]
        [NUnit.Framework.CategoryAttribute("longrun")]
        public async System.Threading.Tasks.Task Long_RunningStabilityTestAt200MsgSFor2Minutes()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "longrun"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Long-running stability test at 200 msg/s for 2 minutes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
        await testRunner.GivenAsync("the scenario name is \"stability_2min\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
        await testRunner.AndAsync("the report output directory is \"perf_reports\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table47.AddRow(new string[] {
                            "Topic",
                            "custom-topic"});
                table47.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table47.AddRow(new string[] {
                            "Queue Size",
                            "100000"});
#line 44
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table47, "And ");
#line hidden
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table48.AddRow(new string[] {
                            "Topic",
                            "custom-topic"});
                table48.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table48.AddRow(new string[] {
                            "Poll Interval",
                            "25"});
#line 49
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table48, "And ");
#line hidden
#line 54
        await testRunner.AndAsync("a constant load of 200 messages per second for 120 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
        await testRunner.WhenAsync("the performance measurement is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Measure latency at low rate (10 msg/s)")]
        [NUnit.Framework.CategoryAttribute("performance")]
        [NUnit.Framework.CategoryAttribute("lowrate")]
        public async System.Threading.Tasks.Task MeasureLatencyAtLowRate10MsgS()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "lowrate"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Measure latency at low rate (10 msg/s)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
        await testRunner.GivenAsync("the scenario name is \"latency_low_rate\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
        await testRunner.AndAsync("the report output directory is \"perf_reports\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table49.AddRow(new string[] {
                            "Topic",
                            "default"});
                table49.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table49.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
#line 61
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table49, "And ");
#line hidden
                global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table50.AddRow(new string[] {
                            "Topic",
                            "default"});
                table50.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table50.AddRow(new string[] {
                            "Poll Interval",
                            "10"});
#line 66
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table50, "And ");
#line hidden
#line 71
        await testRunner.AndAsync("a constant load of 10 messages per second for 60 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
        await testRunner.WhenAsync("the performance measurement is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
