// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Schema Registry compatibility enforcement")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SchemaRegistryCompatibilityEnforcementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Schema Registry compatibility enforcement", "    These scenarios verify that Schema Registry accepts legal schema updates\n    " +
                "for a given CompatibilityMode, independent of subscriber message processing.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SchemaRegistryCompatibility.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BACKWARD accepts removing a field (new schema registration succeeds)")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_BACKWARD")]
        public async System.Threading.Tasks.Task BACKWARDAcceptsRemovingAFieldNewSchemaRegistrationSucceeds()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_BACKWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BACKWARD accepts removing a field (new schema registration succeeds)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table65.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table65.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table65.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table65.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table65.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("publisher oldSchemaPublisher of type \"TestEventWithAdditionalField\" is configured" +
                        " with the following options:", ((string)(null)), table65, "Given ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table66.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table66.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table66.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table66.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table66.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 14
        await testRunner.AndAsync("publisher newSchemaPublisher of type \"TestEvent\" is configured with the following" +
                        " options:", ((string)(null)), table66, "And ");
#line hidden
#line 21
        await testRunner.WhenAsync("the publisher oldSchemaPublisher sends message \"seed\" priority 0 to topic \"test-t" +
                        "opic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
        await testRunner.ThenAsync("publish succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
        await testRunner.WhenAsync("the publisher newSchemaPublisher sends message \"legal-update\" to topic \"test-topi" +
                        "c\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
        await testRunner.ThenAsync("publish succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FORWARD accepts adding a new field (new schema registration succeeds)")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_FORWARD")]
        public async System.Threading.Tasks.Task FORWARDAcceptsAddingANewFieldNewSchemaRegistrationSucceeds()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_FORWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FORWARD accepts adding a new field (new schema registration succeeds)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table67.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table67.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table67.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table67.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table67.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 28
        await testRunner.GivenAsync("publisher oldSchemaPublisher of type \"TestEvent\" is configured with the following" +
                        " options:", ((string)(null)), table67, "Given ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table68.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table68.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table68.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table68.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table68.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 35
        await testRunner.AndAsync("publisher newSchemaPublisher of type \"TestEventWithAdditionalField\" is configured" +
                        " with the following options:", ((string)(null)), table68, "And ");
#line hidden
#line 42
        await testRunner.WhenAsync("the publisher oldSchemaPublisher sends message \"seed\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
        await testRunner.ThenAsync("publish succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
        await testRunner.WhenAsync("the publisher newSchemaPublisher sends message \"legal-update\" priority 0 to topic" +
                        " \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
        await testRunner.ThenAsync("publish succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BACKWARD rejects adding required field without default (new schema registration f" +
            "ails)")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_BACKWARD")]
        public async System.Threading.Tasks.Task BACKWARDRejectsAddingRequiredFieldWithoutDefaultNewSchemaRegistrationFails()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_BACKWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BACKWARD rejects adding required field without default (new schema registration f" +
                    "ails)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table69.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table69.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table69.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table69.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table69.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 49
        await testRunner.GivenAsync("publisher oldSchemaPublisher of type \"TestEvent\" is configured with the following" +
                        " options:", ((string)(null)), table69, "Given ");
#line hidden
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table70.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table70.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table70.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table70.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table70.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 56
        await testRunner.AndAsync("publisher newSchemaPublisher of type \"TestEventWithAdditionalField\" is configured" +
                        " with the following options:", ((string)(null)), table70, "And ");
#line hidden
#line 63
        await testRunner.WhenAsync("the publisher oldSchemaPublisher sends message \"seed\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
        await testRunner.AndAsync("the publisher newSchemaPublisher sends message \"should-fail\" priority 0 to topic " +
                        "\"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.ThenAsync("publish fails with schema incompatibility", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FORWARD rejects removing required field without default (new schema registration " +
            "fails)")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_FORWARD")]
        public async System.Threading.Tasks.Task FORWARDRejectsRemovingRequiredFieldWithoutDefaultNewSchemaRegistrationFails()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_FORWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FORWARD rejects removing required field without default (new schema registration " +
                    "fails)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table71 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table71.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table71.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table71.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table71.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table71.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 69
        await testRunner.GivenAsync("publisher oldSchemaPublisher of type \"TestEventWithAdditionalField\" is configured" +
                        " with the following options:", ((string)(null)), table71, "Given ");
#line hidden
                global::Reqnroll.Table table72 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table72.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table72.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table72.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table72.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table72.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 76
        await testRunner.AndAsync("publisher newSchemaPublisher of type \"TestEvent\" is configured with the following" +
                        " options:", ((string)(null)), table72, "And ");
#line hidden
#line 83
        await testRunner.WhenAsync("the publisher oldSchemaPublisher sends message \"seed\" priority 0 to topic \"test-t" +
                        "opic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
        await testRunner.AndAsync("the publisher newSchemaPublisher sends message \"should-fail\" to topic \"test-topic" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
        await testRunner.ThenAsync("publish fails with schema incompatibility", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
