// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Schema Full compatibility upgrade paths")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SchemaFullCompatibilityUpgradePathsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Schema Full compatibility upgrade paths", "    These scenarios combine Schema Registry enforcement (FULL) with end-to-end pu" +
                "blish/subscribe flow.\n    We keep them split into two directions", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SchemaFullCompatibility.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FULL A→B - old subscriber reads messages after schema adds a field with default")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_FULL")]
        public async System.Threading.Tasks.Task FULLAB_OldSubscriberReadsMessagesAfterSchemaAddsAFieldWithDefault()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_FULL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FULL A→B - old subscriber reads messages after schema adds a field with default", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table63.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table63.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table63.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table63.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("a subscriber of type \"TestEvent\" is configured with the following options:", ((string)(null)), table63, "Given ");
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table64.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table64.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table64.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table64.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table64.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 13
        await testRunner.GivenAsync("publisher oldPub of type \"TestEvent\" is configured with the following options:", ((string)(null)), table64, "Given ");
#line hidden
#line 20
        await testRunner.WhenAsync("the publisher oldPub sends message \"seed\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table65.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table65.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table65.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table65.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table65.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 22
        await testRunner.GivenAsync("publisher newPub of type \"TestEventWithAdditionalDefaultField\" is configured with" +
                        " the following options:", ((string)(null)), table65, "Given ");
#line hidden
#line 29
        await testRunner.WhenAsync("the publisher newPub sends message \"message-content\" priority 0 to topic \"test-to" +
                        "pic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FULL B→A - old subscriber reads messages after schema removes a defaulted field")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_FULL")]
        public async System.Threading.Tasks.Task FULLBA_OldSubscriberReadsMessagesAfterSchemaRemovesADefaultedField()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_FULL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FULL B→A - old subscriber reads messages after schema removes a defaulted field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table66.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table66.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table66.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table66.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 34
        await testRunner.GivenAsync("a subscriber of type \"TestEventWithAdditionalDefaultField\" is configured with the" +
                        " following options:", ((string)(null)), table66, "Given ");
#line hidden
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table67.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table67.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table67.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table67.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table67.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 40
        await testRunner.GivenAsync("publisher oldPub of type \"TestEventWithAdditionalDefaultField\" is configured with" +
                        " the following options:", ((string)(null)), table67, "Given ");
#line hidden
#line 47
        await testRunner.WhenAsync("the publisher oldPub sends message \"seed\" priority 0 to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table68.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table68.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table68.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table68.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table68.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 49
        await testRunner.GivenAsync("publisher newPub of type \"TestEvent\" is configured with the following options:", ((string)(null)), table68, "Given ");
#line hidden
#line 56
        await testRunner.WhenAsync("the publisher newPub sends message \"message-content\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
        await testRunner.ThenAsync("the subscriber receives message \"message-content\" with default priority", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
