
//  <auto-generated>

#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Schema backward compatibility - subscriber with newer schema reads messages from " +
        "a publisher using old schema")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SchemaBackwardCompatibility_SubscriberWithNewerSchemaReadsMessagesFromAPublisherUsingOldSchemaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Schema backward compatibility - subscriber with newer schema reads messages from " +
                "a publisher using old schema", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SchemaBackwardCompatibility.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("New schema has a new field with a default value")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_BACKWARD")]
        public async System.Threading.Tasks.Task NewSchemaHasANewFieldWithADefaultValue()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_BACKWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("New schema has a new field with a default value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table51.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table51.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table51.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table51.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table51.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 6
        await testRunner.GivenAsync("a publisher of type \"TestEvent\" is configured with the following options:", ((string)(null)), table51, "Given ");
#line hidden
                global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table52.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table52.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table52.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table52.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 13
        await testRunner.AndAsync("a subscriber of type \"TestEventWithAdditionalDefaultField\" is configured with the" +
                        " following options:", ((string)(null)), table52, "And ");
#line hidden
                global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table53.AddRow(new string[] {
                            "p1"});
#line 19
        await testRunner.WhenAsync("the publisher sends a message", ((string)(null)), table53, "When ");
#line hidden
#line 22
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A field has been removed from the new schema")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_BACKWARD")]
        public async System.Threading.Tasks.Task AFieldHasBeenRemovedFromTheNewSchema()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_BACKWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A field has been removed from the new schema", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table54.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table54.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table54.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table54.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table54.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 26
        await testRunner.GivenAsync("a publisher of type \"TestEventWithAdditionalField\" is configured with the followi" +
                        "ng options:", ((string)(null)), table54, "Given ");
#line hidden
                global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table55.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table55.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table55.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table55.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 33
        await testRunner.AndAsync("a subscriber of type \"TestEvent\" is configured with the following options:", ((string)(null)), table55, "And ");
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table56.AddRow(new string[] {
                            "p1"});
                table56.AddRow(new string[] {
                            "5"});
#line 39
         await testRunner.WhenAsync("the publisher sends a message", ((string)(null)), table56, "When ");
#line hidden
#line 43
        await testRunner.ThenAsync("the subscriber receives message \"p1\" from topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
