// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Schema Forward compatibility")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SchemaForwardCompatibilityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Schema Forward compatibility", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SchemaForwardCompatibility.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscriber with old schema reads message serialized with new schema with addition" +
            "al field")]
        public async System.Threading.Tasks.Task SubscriberWithOldSchemaReadsMessageSerializedWithNewSchemaWithAdditionalField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subscriber with old schema reads message serialized with new schema with addition" +
                    "al field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table58 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table58.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table58.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table58.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table58.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 4
        await testRunner.GivenAsync("a subscriber of type \"TestEvent\" is configured with the following options:", ((string)(null)), table58, "Given ");
#line hidden
                global::Reqnroll.Table table59 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table59.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table59.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table59.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table59.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table59.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 10
        await testRunner.AndAsync("a publisher of type \"TestEventWithAdditionalField\" is configured with the followi" +
                        "ng options:", ((string)(null)), table59, "And ");
#line hidden
#line 17
        await testRunner.WhenAsync("the publisher sends message \"message-content\" priority 0 to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscriber with old schema reads message serialized with new schema with removed " +
            "field that had a default value")]
        public async System.Threading.Tasks.Task SubscriberWithOldSchemaReadsMessageSerializedWithNewSchemaWithRemovedFieldThatHadADefaultValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subscriber with old schema reads message serialized with new schema with removed " +
                    "field that had a default value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table60.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table60.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table60.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table60.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 21
        await testRunner.GivenAsync("a subscriber of type \"TestEventWithAdditionalDefaultField\" is configured with the" +
                        " following options:", ((string)(null)), table60, "Given ");
#line hidden
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table61.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table61.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table61.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table61.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table61.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 27
        await testRunner.AndAsync("a publisher of type \"TestEvent\" is configured with the following options:", ((string)(null)), table61, "And ");
#line hidden
#line 34
        await testRunner.WhenAsync("the publisher sends message \"message-content\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
        await testRunner.ThenAsync("the subscriber receives message \"message-content\" with default priority", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FORWARD rejects removing required field without default (new schema registration " +
            "fails)")]
        [NUnit.Framework.CategoryAttribute("schemaRegistryMode_FORWARD")]
        public async System.Threading.Tasks.Task FORWARDRejectsRemovingRequiredFieldWithoutDefaultNewSchemaRegistrationFails()
        {
            string[] tagsOfScenario = new string[] {
                    "schemaRegistryMode_FORWARD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FORWARD rejects removing required field without default (new schema registration " +
                    "fails)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table62.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table62.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table62.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table62.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table62.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 39
        await testRunner.GivenAsync("publisher oldSchemaPublisher of type \"TestEventWithAdditionalField\" is configured" +
                        " with the following options:", ((string)(null)), table62, "Given ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table63.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table63.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table63.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table63.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table63.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 46
        await testRunner.AndAsync("publisher newSchemaPublisher of type \"TestEvent\" is configured with the following" +
                        " options:", ((string)(null)), table63, "And ");
#line hidden
#line 53
        await testRunner.WhenAsync("the publisher oldSchemaPublisher sends message \"seed\" priority 0 to topic \"test-t" +
                        "opic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
        await testRunner.AndAsync("the publisher newSchemaPublisher sends message \"should-fail\" to topic \"test-topic" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
        await testRunner.ThenAsync("publish fails with schema incompatibility", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
