// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Schema Forward compatibility")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SchemaForwardCompatibilityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Schema Forward compatibility", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SchemaForwardCompatibility.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscriber with old schema reads message serialized with new schema with addition" +
            "al field")]
        public async System.Threading.Tasks.Task SubscriberWithOldSchemaReadsMessageSerializedWithNewSchemaWithAdditionalField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subscriber with old schema reads message serialized with new schema with addition" +
                    "al field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
        await testRunner.GivenAsync("schema \"v2_priority_int_no_default\" is registered for topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table33.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table33.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table33.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table33.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table33.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 5
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table33, "And ");
#line hidden
#line 12
        await testRunner.WhenAsync("the publisher sends message \"message-content\" priority 0 to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
        await testRunner.AndAsync("schema \"v1\" is registered for topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table34.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table34.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table34.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table34.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 14
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table34, "And ");
#line hidden
#line 20
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscriber with old schema reads message serialized with new schema with removed " +
            "field that had a default value")]
        public async System.Threading.Tasks.Task SubscriberWithOldSchemaReadsMessageSerializedWithNewSchemaWithRemovedFieldThatHadADefaultValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subscriber with old schema reads message serialized with new schema with removed " +
                    "field that had a default value", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
        await testRunner.GivenAsync("schema \"v2_priority_int_default_0\" is registered for topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table35.AddRow(new string[] {
                            "Topic",
                            "test-topic"});
                table35.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table35.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table35.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 24
        await testRunner.AndAsync("a subscriber is configured with the following options:", ((string)(null)), table35, "And ");
#line hidden
#line 30
        await testRunner.WhenAsync("schema \"v1\" is registered for topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table36.AddRow(new string[] {
                            "topic",
                            "test-topic"});
                table36.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table36.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table36.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table36.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 31
        await testRunner.AndAsync("a publisher is configured with the following options:", ((string)(null)), table36, "And ");
#line hidden
#line 38
        await testRunner.AndAsync("the publisher sends message \"message-content\" to topic \"test-topic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.ThenAsync("the subscriber successfully receives 1 messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
