// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddE2eTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Subscriber Offset Positions")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SubscriberOffsetPositionsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Subscriber Offset Positions", "    As a system integrator\n    I want to verify that multiple subscribers maintai" +
                "n their own positions independently\n    So that each subscriber can consume mess" +
                "ages at its own pace without affecting others", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SubscriberOffsetPositions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribers maintain their own positions")]
        public async System.Threading.Tasks.Task SubscribersMaintainTheirOwnPositions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subscribers maintain their own positions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table60.AddRow(new string[] {
                            "Topic",
                            "default"});
                table60.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9096"});
                table60.AddRow(new string[] {
                            "Queue Size",
                            "1000"});
                table60.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
                table60.AddRow(new string[] {
                            "Max Send Attempts",
                            "3"});
#line 7
        await testRunner.GivenAsync("a publisher is configured with the following options:", ((string)(null)), table60, "Given ");
#line hidden
#line 14
        await testRunner.AndAsync("11 messages have been published to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table61.AddRow(new string[] {
                            "Topic",
                            "default"});
                table61.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table61.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table61.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 15
        await testRunner.AndAsync("subscriber S1 is configured starting at offset 11 with the following options:", ((string)(null)), table61, "And ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table62.AddRow(new string[] {
                            "Topic",
                            "default"});
                table62.AddRow(new string[] {
                            "Broker",
                            "127.0.0.1:9098"});
                table62.AddRow(new string[] {
                            "Poll Interval",
                            "100"});
                table62.AddRow(new string[] {
                            "Max Retry Attempts",
                            "3"});
#line 21
        await testRunner.AndAsync("subscriber S2 is configured starting at offset 5 with the following options:", ((string)(null)), table62, "And ");
#line hidden
#line 27
        await testRunner.WhenAsync("the publisher sends message \"m11\" to topic \"default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
        await testRunner.ThenAsync("subscriber S1 should receive only message \"m11\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Message"});
                table63.AddRow(new string[] {
                            "msg5"});
                table63.AddRow(new string[] {
                            "msg6"});
                table63.AddRow(new string[] {
                            "msg7"});
                table63.AddRow(new string[] {
                            "msg8"});
                table63.AddRow(new string[] {
                            "msg9"});
                table63.AddRow(new string[] {
                            "msg10"});
                table63.AddRow(new string[] {
                            "m11"});
#line 29
        await testRunner.AndAsync("subscriber S2 should receive messages \"msg5\" to \"m11\":", ((string)(null)), table63, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
